conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('logout', views.loggingOut, name='logout'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path("__reload__/", include("django_browser_reload.urls")),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
	 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

cssText = 'block w-full rounded-md border-0 h-10 px-3 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6'


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': cssText
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': cssText
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': cssText
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': cssText
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': cssText
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': cssText
    }))

core/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.core.mail import send_mail


from item.models import Category, Item

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

from django.contrib.auth import logout

def loggingOut(request) : 
        logout(request)
        return  redirect("/login/")

def subscribe(request):
    email = request.GET.get('email', '')  # Get the 'email' parameter from the URL

    # You can now use the 'email' variable in your view logic
    # For example, you can store it in a database, send a confirmation email, etc.
    subject = 'Welcome To ADF community'
    message = f'Thank you for registering in our Community.'
    email_from = settings.EMAIL_HOST_USER
    recipient_list = [email, ]
    send_mail( subject, message, email_from, recipient_list )

    return render(request ,  'core/subscribe.html' , {'email' : email})

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} |Django </title>
    </head>

    <body>
        <nav class="bg-gray-800 h-15 shadow-lg shadow-inner">
			<div class="mx-3 max-w-7xl px-2 sm:px-6 lg:px-8">
			  <div class="relative flex h-16 items-center justify-between">
				<div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
				  <!-- Mobile menu button-->
					<!--
					  Icon when menu is closed.
		  
					  Menu open: "hidden", Menu closed: "block"
					-->
					<svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
					  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
					</svg>
					<!--
					  Icon when menu is open.
		  
					  Menu open: "block", Menu closed: "hidden"
					-->
					<svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
					  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
					</svg>
				  </button>
				</div>
				<div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
				  <div class="flex flex-shrink-0 items-center">
					<!-- <img class="h-8 w-auto rounded-md" src="https://res.cloudinary.com/hilnmyskv/image/upload/q_70,f_auto/v1683729897/Algolia_com_Blog_assets/Featured_images/ecommerce/what-is-an-online-marketplace/lnywag1uuexthf29as0l.jpg" alt="Your Company"> -->
<h4 class="mb-4  mt-2 text-3xl text-center text-gray-900 dark:text-white md:text-5xl lg:text-3xl "><span class="text-transparent bg-clip-text bg-gradient-to-r to-blue-600 from-violet-200 font-extrabold">Made With Django</span></h4>
				  
        </div>
				  <div class="hidden sm:ml-6 sm:block">
					<div class="flex space-x-3 mt-2">
					  <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
					  <a href="{% url 'item:items' %}" class="bg-gray-900 text-white hover:bg-gray-700 rounded-md px-3 py-2 text-1xl font-medium">Browse</a>

                      {% if request.user.is_authenticated %}
        					  <a href="{% url 'item:new' %}" class="bg-gray-900 text-white hover:bg-gray-700 rounded-md px-3 py-2 text-1xl font-medium">New Item</a>
                    <a href="{% url 'conversation:inbox' %}" class="bg-gray-900 text-white hover:bg-gray-700 rounded-md px-3 py-2 text-1xl font-medium">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="bg-gray-900 text-white hover:bg-gray-700 rounded-md px-3 py-2 text-1xl font-medium">Dashboard</a>
      
                    <div class="absolute mt-1 -mx-5 -right-80 font-extrabold text-slate-50 ">
                        <a href="/logout">
                            <div class="rounded overflow-hidden shadow-lg">
                                <img class="w-8 bg-slate-50" src="https://cdn.icon-icons.com/icons2/2518/PNG/512/logout_icon_151219.png" alt="Logout">
                            </div>
                        </a>
                      </div>

                      <div class="absolute mt-1 -right-40 font-extrabold text-slate-50 ">
                        <a href="/">
                            <div class="rounded overflow-hidden shadow-lg">
                                <img class="w-8 bg-slate-50" src="https://static.vecteezy.com/system/resources/thumbnails/000/568/450/small/vector60-1781-01.jpg" alt="home">
                            </div>
                        </a>
                      </div>

                    <div class="absolute py-1 -right-0 font-medium text-slate-50 text-2xl">{{ user.get_username }}</div>


                    {% else %}
                    <a href="{% url 'core:signup' %}" class="bg-gray-900 text-white hover:bg-gray-700 rounded-md px-3 py-2 text-1xl font-medium">Sign up</a>
                    <a href="{% url 'core:login' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-1xl font-bold">Log in</a>
                    {% endif %}

					</div>
				  </div>
				</div>
				

				</div>
			  </div>
			</div>
		  </nav>




        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

<script>
function appendEmailAndRedirect(event) {
    event.preventDefault(); // Prevent the form from submitting normally

    const emailInput = document.getElementById("emailSub");
    const emailValue = emailInput.value;

    // Append the email as a query parameter to the URL
    const subscribeUrl = "http://127.0.0.1:8000/subscribe?email=" + encodeURIComponent(emailValue);

    // Redirect to the subscribe URL
    window.location.href = subscribeUrl;
}
</script>
        <footer class="py-6 px-6 flex items-center w-full bg-slate-900 mt-7 rounded-lg">
          <div class="relative isolate overflow-hidden bg-gray-900 py-16 sm:py-24 lg:py-32 w-full">
            <div class="mx-auto max-w-7xl px-6 lg:px-8">
              <div class="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2">

                <div class="max-w-xl lg:max-w-lg">
                  <h2 class="text-3xl font-bold tracking-tight text-white sm:text-4xl">Subscribe to our newsletter.</h2>
                  <p class="mt-4 text-lg leading-8 text-gray-300">Nostrud amet eu ullamco nisi aute in ad minim nostrud adipisicing velit quis. Duis tempor incididunt dolore.</p>
                  <div class="mt-6 flex max-w-md gap-x-4">
                    
                    <form  onsubmit="appendEmailAndRedirect(event)" method="post">
                      {% csrf_token %}
                    <label for="email-address" class="sr-only">Email address</label>
                    <input id="emailSub" name="emailSub" type="email" autocomplete="email" required class="w-30 flex-auto rounded-md border-0 bg-white/5 px-3.5 py-2 text-white shadow-sm ring-1 ring-inset ring-white/10 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" placeholder="Enter your email">
                      <button type="submit" class="flex-none rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Subscribe</button>
                    </form>

                  </div>
                </div>
                <dl class="grid grid-cols-1 gap-x-8 gap-y-10 sm:grid-cols-2 lg:pt-2">
                  <div class="flex flex-col items-start">
                    <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
                      <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5m-9-6h.008v.008H12v-.008zM12 15h.008v.008H12V15zm0 2.25h.008v.008H12v-.008zM9.75 15h.008v.008H9.75V15zm0 2.25h.008v.008H9.75v-.008zM7.5 15h.008v.008H7.5V15zm0 2.25h.008v.008H7.5v-.008zm6.75-4.5h.008v.008h-.008v-.008zm0 2.25h.008v.008h-.008V15zm0 2.25h.008v.008h-.008v-.008zm2.25-4.5h.008v.008H16.5v-.008zm0 2.25h.008v.008H16.5V15z" />
                      </svg>
                    </div>
                    <dt class="mt-4 font-semibold text-white">Weekly articles</dt>
                    <dd class="mt-2 leading-7 text-gray-400">Non laboris consequat cupidatat laborum magna. Eiusmod non irure cupidatat duis commodo amet.</dd>
                  </div>
                  <div class="flex flex-col items-start">
                    <div class="rounded-md bg-white/5 p-2 ring-1 ring-white/10">
                      <svg class="h-6 w-6 text-white" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M10.05 4.575a1.575 1.575 0 10-3.15 0v3m3.15-3v-1.5a1.575 1.575 0 013.15 0v1.5m-3.15 0l.075 5.925m3.075.75V4.575m0 0a1.575 1.575 0 013.15 0V15M6.9 7.575a1.575 1.575 0 10-3.15 0v8.175a6.75 6.75 0 006.75 6.75h2.018a5.25 5.25 0 003.712-1.538l1.732-1.732a5.25 5.25 0 001.538-3.712l.003-2.024a.668.668 0 01.198-.471 1.575 1.575 0 10-2.228-2.228 3.818 3.818 0 00-1.12 2.687M6.9 7.575V12m6.27 4.318A4.49 4.49 0 0116.35 15m.002 0h-.002" />
                      </svg>
                    </div>
                    <dt class="mt-4 font-semibold text-white">No spam</dt>
                    <dd class="mt-2 leading-7 text-gray-400">Officia excepteur ullamco ut sint duis proident non adipisicing. Voluptate incididunt anim.</dd>
                  </div>
                </dl>
              </div>
            </div>
            <div class="absolute left-1/2 top-0 -z-10 -translate-x-1/2 blur-3xl xl:-top-6" aria-hidden="true">
              <div class="aspect-[1155/678] w-[72.1875rem] bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
            </div>
          </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>The contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-slate-900 md:text-5xl lg:text-6xl ">Latest items</h1>
        <div class="grid grid-cols-4 gap-2">
            {% for item in items %}
              

                <a href="{% url 'item:detail' item.id %}" class="max-w-sm rounded overflow-hidden shadow-lg mt-5">
                    <img class="w-full" src="{{ item.image.url }}" alt="Sunset in the mountains">
                    <div class="px-6 py-4">
                      <div class="font-bold text-xl mb-2">{{ item.name }}</div>
                      <p class="text-gray-700 text-base">
                        {{item.description}}
                      </p>
                    </div>
                    <div class="px-6 pt-4 pb-2">
                      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">Price: {{ item.price }}</span>
                    </div>
                  </a>

            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12  rounded-xl  bg-gradient-to-r to-gray-500 from-gray-300">
        
    <h1 class="flex mb-4 text-blue-00 items-center text-5xl font-extrabold ">Categories</h1>


        <div class="grid grid-cols-5 gap-3">
            {% for category in categories %}
                <div>
                    <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                        <div class="mt-2 mx-2 py-2 px-2 rounded-b-xl  rounded-md bg-white shadow-lg">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}

<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 bg-slate-300 rounded-lg">
	<div class="sm:mx-auto sm:w-full sm:max-w-sm">
	  <img class="mx-auto h-1/2 w-3/4 rounded-xl" src="https://res.cloudinary.com/hilnmyskv/image/upload/q_70,f_auto/v1683729897/Algolia_com_Blog_assets/Featured_images/ecommerce/what-is-an-online-marketplace/lnywag1uuexthf29as0l.jpg"  alt="Your Company" >

    
<h2 class="mb-4 mt-10 text-3xl text-center font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl "><span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">SIGN</span> IN</h2>

	</div>
  
	<div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm ">

		

        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-purple-900 text-gray-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

        
         


       <form method="post" action=".">

		{% csrf_token %}

			<div class="mt-4"> 
			<label class="block text-sm font-medium leading-6 text-gray-900">	Username 	</label>
			<div class="mt-1 ">
                {{ form.username }}
			</div>

            <div class="mt-4"> 
                <label class="block text-sm font-medium leading-6 text-gray-900">	Password   	</label>
                <div class="mt-1">
                    {{ form.password }}
                </div>

		
  
		<div class="mt-5 mb-8">
		  <button type="submit" class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Submit</button>
		</div>

		
	  </form>


  
	 
	<!-- </div> -->
  <!-- </div> -->
</div>
</div>


{% endblock %} 

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8 bg-slate-300 rounded-lg">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
<h2 class="mb-4 mt-10 text-3xl text-center text-gray-900 dark:text-white md:text-5xl lg:text-6xl "><span class="text-transparent bg-clip-text bg-gradient-to-r to-purple-400 from-teal-500 font-extrabold">REGISTER</span></h2>

	  </div>
    
      {% if form.errors or form.non_field_errors %}
      <div class="mb-3 p-6 bg-purple-900 text-gray-100 rounded-xl">
          {% for field in form %}
              {{ field.errors }}
          {% endfor %}

          {{ form.non_field_errors }}
      </div>
  {% endif %}


    <div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
    <form method="post" action=".">
        {% csrf_token %}

        <div class="mt-4"> 
            <label class="block text-sm font-medium leading-6 text-gray-900">Username</label>
            <div class="mb-3">
                {{ form.username }}
			</div>
		
           
            <label class="block text-sm font-medium leading-6 text-gray-900">Email</label>
            <div class="mb-4">
                {{ form.email }}
			</div>
		

            <label class="block text-sm font-medium leading-6 text-gray-900">Password</label>
            <div class="mb-4">
                {{ form.password1 }}
			</div>
		


            <label class="block text-sm font-medium leading-6 text-gray-900">Repeat password</label>
            <div class="mb-4">
                {{ form.password2 }}
			</div>

        </div>

        <div class="mt-3">
            <button type="submit" class="flex w-full justify-center mb-7 rounded-md bg-indigo-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">SignUp</button>
          </div>

    </form>

{% endblock %}

core/templates/core/subscribe.html
{% extends 'core/base.html' %}


{% block content %}

<div class="relative isolate overflow-hidden bg-gray-900 py-24 sm:py-32">
	<img src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&crop=focalpoint&fp-y=.8&w=2830&h=1500&q=80&blend=111827&sat=-100&exp=15&blend-mode=multiply" alt="" class="absolute inset-0 -z-10 h-full w-full object-cover object-right md:object-center">
	<div class="hidden sm:absolute sm:-top-10 sm:right-1/2 sm:-z-10 sm:mr-10 sm:block sm:transform-gpu sm:blur-3xl" aria-hidden="true">
	  <div class="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr from-[#ff4694] to-[#776fff] opacity-20" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
	</div>
	<div class="absolute -top-52 left-1/2 -z-10 -translate-x-1/2 transform-gpu blur-3xl sm:top-[-28rem] sm:ml-16 sm:translate-x-0 sm:transform-gpu" aria-hidden="true">
	  <div class="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr from-[#ff4694] to-[#776fff] opacity-20" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
	</div>
	<div class="mx-auto w-full px-6 lg:px-8">
	  <div class="mx-auto w-full lg:mx-0">
		<h2 class="text-4xl w-full font-bold tracking-tight text-white sm:text-6xl">Email Subscribed Successfully  - {{email}}</h2>
		<p class="mt-6 text-lg leading-8 text-gray-300">

			We are thrilled to welcome you to our Odoo community! Thank you for subscribing to our newsletter.
			Your support means the world to us, and we can't wait to keep you updated with the latest news, exclusive offers, and exciting updates.
		</p>
	  </div>
	  
	</div>
  </div>


  {% endblock %}